sonar.projectKey=visitor-control-system-esp32
sonar.projectName=Visitor Control System ESP32
sonar.projectVersion=1.0

sonar.sources=main,components
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/.vscode/**,**/build/**

sonar.cfamily.compile-commands=build/compile_commands.json
